server:
  port: 8081

spring:
  application:
    name: aspro-web-gateway
  cloud:
    gateway:
      routes:
      - id: aspro-web-admin
        uri: http://localhost:8082
        predicates:
        - Header=application, admin

      - id: aspro-web-api
        uri: http://localhost:8083
        predicates:
          - Header=application, api

