server:
  port: 8012

spring:
  application:
    name: aspro-service-govern
  profiles:
    active: dev
    include: db # sharding,nacos,redis

---
spring:
  profiles: test
  cloud:
    nacos:
      config:
        extension-configs:
          - data-id: aspro-service-govern.yaml
            group: aspro
            refresh: true