server:
  port: 8002

spring:
  application:
    name: aspro-web-admin
  profiles:
    active: dev
#    include:
#      - db
#      - nacos
#      - redis

# dev profile
---
spring:
  profiles: dev
  cloud:
    nacos:
      config:
        extension-configs:
          - data-id: aspro-web-admin.yaml
            group: aspro
            refresh: true